name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install git-core gnupg flex bison
          mkdir -p $HOME/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > $HOME/bin/repo
          chmod a+rx $HOME/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH
      - name: Download
        run: |
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
          repo sync
      #- name: Compile
      #  run: |
      #    export ALLOW_MISSING_DEPENDENCIES=true
      #    mka recoveryimage
